# Generated by Django 2.0.7 on 2018-07-15 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alternative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Wording', models.CharField(default='', max_length=200)),
                ('Value', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Vote_Count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Alternative', models.CharField(default='', max_length=200)),
                ('Value', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
        migrations.AddField(
            model_name='election',
            name='Description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='election',
            name='Election_Method',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='election',
            name='Owner',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='election',
            name='Vote_Count',
            field=models.IntegerField(default=0),
        ),
    ]
