# Generated by Django 2.0.7 on 2018-07-20 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0002_auto_20180715_1958'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vote_Count',
            new_name='Vote',
        ),
    ]
