# Generated by Django 2.0.7 on 2018-07-20 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0003_auto_20180720_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='alternative',
            name='Election_Number',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='election',
            name='Election_Number',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='vote',
            name='Election_Number',
            field=models.CharField(default='', max_length=200),
        ),
    ]
