# Generated by Django 2.0.7 on 2018-07-20 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0005_auto_20180720_1131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='election',
            old_name='Election_ÌD',
            new_name='Election_ID',
        ),
    ]
