# Generated by Django 2.0.7 on 2018-07-23 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0007_election_number_of_alternatives'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Election_ID', models.CharField(default='', max_length=200)),
                ('Name', models.CharField(default='', max_length=200)),
                ('Description', models.TextField(default='')),
                ('Vote_Count', models.IntegerField(default=0)),
                ('Election_Method', models.CharField(default='', max_length=200)),
                ('Number_Of_Alternatives', models.IntegerField(default=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='election',
            name='Number_Of_Alternatives',
        ),
        migrations.AddField(
            model_name='election',
            name='Number_Of_Questions',
            field=models.IntegerField(default=0),
        ),
    ]
