# Generated by Django 2.0.7 on 2018-07-23 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0008_auto_20180723_0925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alternative',
            name='Election_ID',
        ),
        migrations.AddField(
            model_name='alternative',
            name='Question_ID',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='question',
            name='Question_ID',
            field=models.CharField(default='', max_length=200),
        ),
    ]
