# Generated by Django 2.0.7 on 2018-07-23 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0009_auto_20180723_0926'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='Name',
            new_name='Owner',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='Description',
            new_name='Wording',
        ),
        migrations.AddField(
            model_name='alternative',
            name='Owner',
            field=models.CharField(default='', max_length=200),
        ),
    ]
